### ISSUE TITLE
Can you add ansible awx to docker container?

### ISSUE THREAD

**Issue by abohnenberger** [bluxmit/alnoda-workspaces#13]
I think what you did was great as I was spending a lot of time reinstalling these tools. Is it possible to add AWS AWX to the container. Jenkins would be nice as well or gitlab. I know  you hide secrets with ansible vault but it so much easier with awx.

**Comment by amlucent** [comment]
Can I further suggest, Hashicorp Vault instead for secrets management instead of ansible vault.  Much more fully featured and multi-user and since this container already has terraform its kind of "on brand" so to speak.

Im less in favor of a built in git, I personally think that should be a separate container as so many people will chose to use a cloud solution like github.  Git lab especially is kind of big and resource hungry.

**Comment by bluxmit** [comment]
Hi, these features were not considered for implementation so far, closing the issue
