### ISSUE TITLE
OSX port 8021 | ftp-proxy.plist

### ISSUE THREAD

**Issue by bwearp** [bluxmit/alnoda-workspaces#3]
Thanks for publishing. Looks awesome.

Apple has a service listening on port 8021....

https://apple.stackexchange.com/questions/404346/what-is-intu-ec-client-listening-on-tcp-port-8021

"sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.ftp-proxy.plist does the job of stopping the service."

**Comment by bluxmit** [comment]
Thank you for noticing. Somehow I am using a mac os 10.14.x, and this application is not running. 
You can always start a workspace with different ports rather than the standard 8020-8035. For example, if you want to use python workspace on ports 9020-9035, execute `docker run --name space-2 -d -p 9020-9035:8020-8035 -e ENTRY_PORT=9020 alnoda/python-workspace`. Same applies to all other workspaces.

**Comment by bluxmit** [comment]
closing as solved
